services:
  messenger-db:
    image: postgres:17-alpine
    ports:
      - "10000:5432"
    environment:
      - "POSTGRES_DB=delivery_db"
      - "POSTGRES_USER=delivery"
      - "POSTGRES_PASSWORD=delivery"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery -d delivery"]
      interval: 1s
      timeout: 5s
      retries: 10